### ISSUE TITLE
The pop is missing

### ISSUE THREAD

**Issue by sofer** [nelsonic/google-apps-certification#11]
_"If people on the Google Apps training decide they want to challenge themselves to learn development skills (thus unlocking the most in-demand career opportunities) we can help coach them further after they complete this initial training."_

This needs to be emphasised more. IT courses for the unemployed, "Employability Level 1 and Level 2", are two-a-penny and they do not have a good record of getting people jobs. 

But our ability to "coach them further" is what sets us apart from _everyone_ else.

**Comment by nelsonic** [comment]
Agreed. :+1: 
Paul is unlikely to look at this over the weekend.
So if you have time to PR tomorrow after your busy day, please do. 
Thanks!

**Comment by sofer** [comment]
@nelsonic PR awaiting your attention.
