### ISSUE TITLE
Transferrable skills | Office <-> Google Docs

### ISSUE THREAD

**Issue by iteles** [nelsonic/google-apps-certification#5]
For Google Docs specifically, whichever one you learn first will give you the core concepts you need to learn the other, i.e.
- What is a word processor?
- What are fonts?
- What is font formatting?
- Margins, print margins
- Introducing tables into word processing
- etc, etc

So learning Google Docs creates an additional transferrable skill and whichever one you learn second (Office or Google Docs) solidifies your knowledge in the concepts of the first.

**Comment by nelsonic** [comment]
Please PR this and any other learning objectives into the Readme when you get a chance.

**Comment by nelsonic** [comment]
<img width="827" alt="list-of-google-apps-2015" src="https://cloud.githubusercontent.com/assets/194400/10400595/891cb624-6eb1-11e5-9820-3eedb6c971d4.png">

**Comment by nelsonic** [comment]
Do you still plan on adding curriculum details?
or can we just ship this to Paul and add detail later?

**Comment by iteles** [comment]
No, you've already added the portion of transferable skills in your latest commit so I'm happy to close this - that was the main purpose of the issue.
